on: [pull_request]

jobs:
  # Use separate jobs for different databases, otherwise the failed step will block other following steps
  mysql-sql-review:
    runs-on: ubuntu-latest
    name: MySQL SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check MySQL
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          override-file-path: ./sql/sql-review-override.yml
          database-type: MYSQL
          file-pattern: ^sql/.*\.sql$
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.0.6"
          sqlfluff_command: "lint" # Or "lint"
          paths: '${{ github.workspace }}/sql/myfirstdb'
          dialect: 'mysql'
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=0 docker build -t init-db .
      - name: Start MySQL
        run: |
          set -e
          docker run --rm -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql:5.7 
      - name: DB Migrate
        run: |
          set -e
          docker run --name init-db \
            -e INIT_DB_TYPE=mysql -e INIT_DB_HOST=172.17.0.1 -e INIT_DB_PORT=3306 \
            -e INIT_DB_USER=root -e INIT_DB_PASSWORD=my-secret-pw \
            init-db   
