on: [pull_request]

jobs:
  # Use separate jobs for different databases, otherwise the failed step will block other following steps
  mysql-sql-review:
    runs-on: ubuntu-latest
    name: MySQL SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check MySQL
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          override-file-path: ./sql/sql-review-override.yml
          database-type: MYSQL
          file-pattern: ^sql/.*\.sql$
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=0 docker build -t init-db .
      - name: Start MySQL
        run: |
          set -e
          docker run --rm -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql:5.7 
      - name: DB Migrate Up
        run: |
          set -e
          docker run --rm --name init-db \
            -e INIT_DB_TYPE=mysql -e INIT_DB_HOST=172.17.0.1 -e INIT_DB_PORT=3306 \
            -e INIT_DB_USER=root -e INIT_DB_PASSWORD=my-secret-pw \
            init-db   
      - name: DB Migrate Down
        run: |
          set -e
          docker run --rm --name init-db \
            -e INIT_DB_TYPE=mysql -e INIT_DB_HOST=172.17.0.1 -e INIT_DB_PORT=3306 \
            -e INIT_DB_USER=root -e INIT_DB_PASSWORD=my-secret-pw \
            init-db -c "cd /usr/bin/app/sql && ./run.sh down myfirstdb 20240517001"
